# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "2fa92ea70a6eabcfac412c7e99df9b8413eba353"

[[deps.DrugInterface]]
path = "."
uuid = "ecbac44d-373e-48a5-bcbb-08f349367545"
version = "0.1.0"
