name = "DrugInterface"
uuid = "ecbac44d-373e-48a5-bcbb-08f349367545"
authors = ["Simon Steiger"]
version = "0.2.0"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
